### ISSUE TITLE
ampy.7z seems corrupted?

### ISSUE THREAD

**Issue by codecvlt** [Xenodius/ASI_AmpyDisplay#1]
I used 7z to extract the ampy.img file, but I cannot flash it with etcher or gnome-disks

**Comment by cwkowalski** [comment]
Strange, it's been a long time since I test-flashed it, but I believe it worked fine for me. It might be corrupted, I didn't re-download it and I can't test it at the moment as I don't have a spare Pi right now but I have been working to create another image ASAP. 

Until about a week ago I'd only benchtested this display with my system cause ASI took months to return my controller. I've found a few new bugs now that I'm on the road with it (biggest is that negative/regen controller current and speed values sometimes are calculated as huge positive values)... but I also managed to nearly halve CPU usage so it runs smooth even with some thermal throttling on my pi4. Should merge this branch ("exp") to master in a week or so unless something comes up. I just want to squash those bugs and add a couple more setup.csv switches for people without a JBD BMS, or who are not using their BMS in a passthrough configuration, before I create another image file. 

That way, users won't have to git pull after flashing to get a bug-free version that can work with any ASI controller configuration. I would like it to be as simple as buy parts, assemble, flash, connect, ride.

**Comment by codecvlt** [comment]
Ya man this a great project. Keep it up. Just got a bac4000 for my Surron from teznic. No display support so figured I'd give this a go. You think it would run ok on a pi zero w?

**Comment by cwkowalski** [comment]
I'm not sure. It might be too slow. I don't have a way to plot CPU usage on piCore, and I don't know exactly how much the throttling holds it back, but it's real hot where I am and before some of the optimization the Pi4 was basically unresponsive once it got over 70c. I have a passive heatsink and paste only, and its inside my Q140 frame with no ventilation, right next to the battery which can get up to 35-40C. Took an hour of riding in full sun 90+ degrees F before it really slowed down. Now it uses less than half as much CPU time. In terms of total clock time that can be used (3 processes on 1.5ghz cores vs. 1.0ghz single core) there's a considerable difference between them, though.

However, even after optimization about 3/4ths of the processing time comes from calculating running averages/maxima/minima for several of the stats (18000 values for last 5 minutes, per statistic). That can be disabled with a single comment and may be enough to make it work. If you would like to try it I can help you pare it down, if necessary. I could also help you setup other information to replace those stats in the display scheme if you like-- QtDesigner is pretty easy to use. Alternatively a couple values can be edited to reduce the duration the detailed stats are held for so those series are shorter, e.g. it would take 1/10th as much cpu time to calculate Wh/mi and other vars over just the last 30 seconds vs. 5 minutes.

Personally the biggest thing I love is being able to switch whole power profiles with a flick of a switch. Even if you had to reduce the framerate and some calcs you could still get that on the Zero W, I think. The thing I like least about it, is that it takes around 30 seconds to actually boot up. Small price all considered. I've been having trouble with BacDoor mobile since the replacement controller has a newer 6.019 firmware it doesn't yet support, lol, but I was able to get the controller setup by using debug (pdb.set_trace) over SSH on my display and just writing modbus commands. =)

**Comment by codecvlt** [comment]
Ya. Switching profiles is def a nice feature. Really love the customization aspect of the UI too. Would love to try a paired down version with maybe less of the statistics gathering. At the very least if the zero doesn't stand up to test I have a pi4 kicking around I can try next. The boot time thing is tough yea. I'm a noob with Arduino so circuit python might be a bit more than I'm willing to dive deep on . So the 30 sec boot time might not be too much of an issue.

**Comment by cwkowalski** [comment]
Cool, I'll reply here when I update the image. Fingers crossed. Work's crazy.

**Comment by codecvlt** [comment]
I hear ya. I work in software too, I'm impressed with what you got put together here. Was fun reading the forum updates.

**Comment by codecvlt** [comment]
Ah jeez, so figured out the issue. I was running etcher as non-root. Am currently in the process of flashing my SD card now.

**Comment by cwkowalski** [comment]
> Ah jeez, so figured out the issue. I was running etcher as non-root. Am currently in the process of flashing my SD card now.

Let me know if you manage to run it on there. If it's too slow you may want to go to ~line 669, try reducing self.mean_length increasing iter_long_threshold. The main iter/iter_threshold should run ~20hz and update the gui each time, you can try increasing iter_threshold to 6 which will reduce resources used considerably but also reduce FPS to ~10hz. 

After you flash it and before you bother editing iterators, connect to your local wifi then enter:
`filetool.sh -b`
it will try to autoconnect to saved WiFi on boot if any are available, but you need that command to make any changes persist on the next boot. I recommend using your home and a wireless hotspot in case you want remote terminal access from a mobile device once installed, e.g. to check logs. If the program crashes there is a log written to /tmp/ampylog.txt.

I have fixed a few bugs in the 'exp' branch, biggest is 2's complement to some registers so it can understand negative speed/current without and not mess up stats, so once you're on wifi you can use; 
`tce-load -i git
cd /mnt/mmcblk0p2/ASI_AmpyDisplay
sudo git checkout exp
sudo git pull`

More fixes coming as I manage to find the time. Distance and wh used are not correct but the speedo and wh/mi are accurate... I have some guesses but not certain why yet.

**Comment by cwkowalski** [comment]
> Ah jeez, so figured out the issue. I was running etcher as non-root. Am currently in the process of flashing my SD card now.

FYI I have finally discovered the cause of aforementioned bug, incorrect distance/wh counting but correct speedo and wh/mi. It turns out, while the BAC8000 can handle one serial I/O loop every ~16ms when idle or at pretty low speeds, once it gets up to ~10mph on my motor (only ~2k eRPM!) it starts sending error responses cause it can't keep up. This was the biggest and most perplexing problem I noticed with real-world testing and took me a lot of troubleshooting on the road to find, but it can be fixed while still giving a pretty good refresh rate. So now I just have to mop up a few easier things then I'll repack the ISO, and make a pretty big update to the /master branch from /exp.

**Comment by codecvlt** [comment]
Been fighting trying to get this running on a pi zero. When I used your .img it took super long to load into the OS. So I took a stab at building my own piCore OS. It was going well, until I had to pip install PyQt5. Couldn't for the life of me get it to build. I am using python 3.8. I don't have the error msg on hand as I've kind of shelved the project for now.

I was almost considering trying to tease apart the bits that talk to the controller and build my own UI using something lighter weight, but alas real life gets in the way :)

**Comment by cwkowalski** [comment]
> Been fighting trying to get this running on a pi zero. When I used your .img it took super long to load into the OS. So I took a stab at building my own piCore OS. It was going well, until I had to pip install PyQt5. Couldn't for the life of me get it to build. I am using python 3.8. I don't have the error msg on hand as I've kind of shelved the project for now.
> 
> I was almost considering trying to tease apart the bits that talk to the controller and build my own UI using something lighter weight, but alas real life gets in the way :)

When you say to load into the OS, do you mean boot? Likely boot time cannot be improved further, I cut out a lot of stuff and piCore is already very barebones. Potentially, it could be improved by using faster storage media. I'd totally forgotten that the version of piCore and most of the extensions are compiled with that specific ARM cpu in mind... I feel you on 'real life'. FYI though I do like my ASI controller I do not think I'll buy another, I plan to turn my dev attention in the near future to VESC controllers. 

In case you decide to try again... I was totally new to compiling when I did it, and I needed a crapload of flags to do it properly... think I had to specify some environmental variables too, to get it to use some dependent packages compiled for piCore, some of which I also had to compile. It took me many tries per package to get a working error-free compile. The most helpful thing for me, was the build notes in the piCore repo. There are tons of examples. e.g. this is for TinyCore but most piCore packages have a build log like this in their /src/... folder. http://tinycorelinux.net/8.x/armv6/tcz/src/glib2/glib2.build
